### PR TITLE
I made changes to clarify 3 areas

### PR DESCRIPTION
**Pull request by silverhoopedge**
1-spelling fix seperate to separate
2-add text use a comma... to be similar to the way tags are set up
3-clarify set up for new taxonomy

### CODE REVIEW

**Comment by jornbakhuys** [comment]
Pull request looks good.

**Comment by silverhoopedge** [comment]
This was my first pull request submitted-ever.Glad it looks good.

```
 On Thursday, July 9, 2015 1:30 AM, Jorn Bakhuys <notifications@github.com> wrote:
```

 Pull request looks good.—

**Comment by jornbakhuys** [comment]
Congrats! :)

**Comment by jornbakhuys** [comment]
See https://github.com/sdsweb/custom-post-type-maker/pull/6 for correct PR.

**Pull request closed without merging**
